another run...

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -54,7 +54,7 @@ jobs:
         with:
           name: GoFileCLI_win-x64
           path: |
-            build/*.exe
+            build/gofilecli.exe
   
   build-linux-x64:
     runs-on: ubuntu-latest
@@ -91,7 +91,7 @@ jobs:
         with:
           name: GoFileCLI_linux-x64
           path: |
-            build/*.bin
+            build/gofilecli.bin
     
   build-macos:
     runs-on: macos-latest
@@ -120,8 +120,8 @@ jobs:
       - name: Build Executable with Nuitka
       # --macos-app-icon=resources/icon.icns
         run: |
-          python -m nuitka --standalone --assume-yes-for-downloads --output-dir=dist --macos-create-app-bundle --macos-target-arch=arm64 gofilecli.py
-          python -m nuitka --standalone --assume-yes-for-downloads --output-dir=dist_x86_64  --macos-create-app-bundle --macos-target-arch=x86_64 gofilecli.py
+          python -m nuitka --onefile --assume-yes-for-downloads --output-dir=dist --macos-target-arch=arm64 gofilecli.py
+          python -m nuitka --onefile --assume-yes-for-downloads --output-dir=dist_x86_64 --macos-target-arch=x86_64 gofilecli.py
 
       - name: Upload Artifact[osx-arm64]
         uses: actions/upload-artifact@v4
@@ -137,96 +137,96 @@ jobs:
           path: |
             dist/*
 
-  create_draft_release:
-    name: Create Github draft release
-    if: ${{ github.event.inputs.doRelease == 'true' }}
-    needs: [build-win-x64,build-linux-x64,build-macos]
-    runs-on: ubuntu-latest
-    steps:
-      - name: Audit gh version
-        run: gh --version
+  # create_draft_release:
+  #   name: Create Github draft release
+  #   if: ${{ github.event.inputs.doRelease == 'true' }}
+  #   needs: [build-win-x64,build-linux-x64,build-macos]
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - name: Audit gh version
+  #       run: gh --version
 
-      - name: Check for existing release
-        id: check_release
-        run: |
-          echo "::echo::on"
-          gh release view --repo '${{ github.repository }}' '${{ github.event.inputs.tag }}' \
-            && echo "already_exists=true" >> $GITHUB_ENV \
-            || echo "already_exists=false" >> $GITHUB_ENV
-        env:
-          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
+  #     - name: Check for existing release
+  #       id: check_release
+  #       run: |
+  #         echo "::echo::on"
+  #         gh release view --repo '${{ github.repository }}' '${{ github.event.inputs.tag }}' \
+  #           && echo "already_exists=true" >> $GITHUB_ENV \
+  #           || echo "already_exists=false" >> $GITHUB_ENV
+  #       env:
+  #         GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
 
-      - name: Checkout repo
-        if: env.already_exists == 'false'
-        uses: actions/checkout@v3
-        with:
-          ref: '${{ github.event.inputs.ref }}'
+  #     - name: Checkout repo
+  #       if: env.already_exists == 'false'
+  #       uses: actions/checkout@v3
+  #       with:
+  #         ref: '${{ github.event.inputs.ref }}'
 
-      - name: Create release
-        if: env.already_exists == 'false'
-        run: >
-          gh release create
-          '${{ github.event.inputs.tag }}'
-          --draft
-          --repo '${{ github.repository }}'
-          --title '${{ github.event.inputs.tag }}'
-          --target '${{ github.event.inputs.ref }}'
-          --generate-notes
-        env:
-          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
+  #     - name: Create release
+  #       if: env.already_exists == 'false'
+  #       run: >
+  #         gh release create
+  #         '${{ github.event.inputs.tag }}'
+  #         --draft
+  #         --repo '${{ github.repository }}'
+  #         --title '${{ github.event.inputs.tag }}'
+  #         --target '${{ github.event.inputs.ref }}'
+  #         --generate-notes
+  #       env:
+  #         GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
 
-  attach_to_release:
-    name: Attach native executables to release
-    if: ${{ github.event.inputs.doRelease == 'true' }}
-    needs: create_draft_release
-    runs-on: ubuntu-latest
-    steps:
-      - name: Get current date
-        id: date
-        run: echo "date=$(date +'%Y%m%d')" >> $GITHUB_ENV
+  # attach_to_release:
+  #   name: Attach native executables to release
+  #   if: ${{ github.event.inputs.doRelease == 'true' }}
+  #   needs: create_draft_release
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - name: Get current date
+  #       id: date
+  #       run: echo "date=$(date +'%Y%m%d')" >> $GITHUB_ENV
         
-      - name: GH version
-        run: gh --version
+  #     - name: GH version
+  #       run: gh --version
       
-      - name: Fetch executables
-        uses: actions/download-artifact@v3
+  #     - name: Fetch executables
+  #       uses: actions/download-artifact@v3
       
-      - name: List downloaded artifacts
-        run: |
-          echo "Listing files in workspace:"
-          ls -al
+  #     - name: List downloaded artifacts
+  #       run: |
+  #         echo "Listing files in workspace:"
+  #         ls -al
       
-          echo "Checking artifact types:"
-          for item in *; do
-            if [ -d "$item" ]; then
-              echo "$item is a directory"
-            elif [ -f "$item" ]; then
-              echo "$item is a file"
-            else
-              echo "$item is neither a file nor a directory"
-            fi
-          done
+  #         echo "Checking artifact types:"
+  #         for item in *; do
+  #           if [ -d "$item" ]; then
+  #             echo "$item is a directory"
+  #           elif [ -f "$item" ]; then
+  #             echo "$item is a file"
+  #           else
+  #             echo "$item is neither a file nor a directory"
+  #           fi
+  #         done
         
-      - name: Tar (linux, macOS)
-        run: for dir in *{osx,linux}*; do
-                if [ -d "$dir" ]; then
-                  tar cvzfp "${dir}_${{ env.date }}.tar.gz" "$dir"
-                fi
-              done
+  #     - name: Tar (linux, macOS)
+  #       run: for dir in *{osx,linux}*; do
+  #               if [ -d "$dir" ]; then
+  #                 tar cvzfp "${dir}_${{ env.date }}.tar.gz" "$dir"
+  #               fi
+  #             done
               
-      - name: Zip (windows)
-        run: for file in *win*; do
-                if [ -f "$file" ]; then
-                  zip -r "${file}_${{ env.date }}.zip" "$file"
-                fi
-              done
+  #     - name: Zip (windows)
+  #       run: for file in *win*; do
+  #               if [ -f "$file" ]; then
+  #                 zip -r "${file}_${{ env.date }}.zip" "$file"
+  #               fi
+  #             done
 
-      - name: Upload
-        run: |
-          until gh release upload --clobber --repo ${{ github.repository }} ${{ github.event.inputs.tag }} *.zip *.tar.gz; do
-            echo "Attempt $((++attempts)) to upload release artifacts failed. Will retry in 20s"
-            sleep 20
-          done
-        timeout-minutes: 10
-        env:
-          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
+  #     - name: Upload
+  #       run: |
+  #         until gh release upload --clobber --repo ${{ github.repository }} ${{ github.event.inputs.tag }} *.zip *.tar.gz; do
+  #           echo "Attempt $((++attempts)) to upload release artifacts failed. Will retry in 20s"
+  #           sleep 20
+  #         done
+  #       timeout-minutes: 10
+  #       env:
+  #         GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
